/** Minimal Tokyo trip seed for the API store (mirrors src/engine/seed.ts). */

export const seed = {
  trip: {
    id: 1,
    name: 'Tokyo long weekend',
    city: 'Tokyo',
    country: 'Japan',
    startDate: '2026-09-01',
    days: 4,
    pace: 'balanced',
    startHour: 9,
    endHour: 21,
    budget: 2200,
    currency: 'USD',
    lat: 35.68,
    lng: 139.76,
    expenses: [
      { id: 1, label: 'Shibuya hotel (4 nights)', category: 'lodging', amount: 640 },
      { id: 2, label: 'Round-trip flights', category: 'transport', amount: 890 },
      { id: 3, label: '72h metro passes ×3', category: 'transport', amount: 45 },
    ],
  },
  tripSpots: [
    {
      id: 1,
      name: 'teamLab Planets',
      category: 'museum',
      lat: 35.649,
      lng: 139.79,
      duration: 120,
      cost: 38,
      rating: 4.8,
      open: 10,
      close: 22,
      source: 'seed',
      tier: 'must',
      votes: 3,
      note: '',
    },
    {
      id: 2,
      name: 'Senso-ji',
      category: 'sight',
      lat: 35.7148,
      lng: 139.7967,
      duration: 75,
      cost: 0,
      rating: 4.6,
      open: 6,
      close: 17,
      source: 'seed',
      tier: 'maybe',
      votes: 2,
      note: '',
    },
    {
      id: 3,
      name: 'Shibuya Crossing',
      category: 'sight',
      lat: 35.6595,
      lng: 139.7004,
      duration: 45,
      cost: 0,
      rating: 4.4,
      open: null,
      close: null,
      source: 'seed',
      tier: null,
      votes: 1,
      note: '',
    },
  ],
};
